#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# NOTE ensure every line ends with a line feed
# shellcheck disable=SC2005
echo "$(/usr/local/bin/chunkc tiling::query -D "$(/usr/local/bin/chunkc tiling::query -m id)")"
# shellcheck disable=SC2005
echo "$(/usr/local/bin/chunkc tiling::query -d id)"
