#!/bin/sh

# xmobar-cpu-usage
# author: Seong Yong-ju <sei40kr@gmail.com>

mpstat -P ALL 1 | awk '
$3 == "all" {
  usage = int(100 - $13)

  s = "<fn=3>﬙</fn><fn=1>  </fn>" usage "%"

  if (30 <= usage) {
    if (usage <= 80) color = "#cc8000"
    else             color = "#cc0080"

    s = "<fc=" color ">" s "</fc>"
  }

  print s
  fflush()
}'
