#!/bin/sh

# xmobar-mem-usage
# author: Seong Yong-ju <sei40kr@gmail.com>

free -ms 1 | awk '
$1 == "Mem:" {
  total = $2 + 0
  used = $3 + 0
  usage = used / total

  s = "<fn=3></fn><fn=1>  </fn>" used "M"

  if (0.30 <= usage) {
    if (usage <= 0.80) color = "#cc8000"
    else               color = "#cc0080"

    s = "<fc=" color ">" s "</fc>"
  }

  print s
  fflush()
}'
