#!/usr/bin/env bash

# xmobar-todoist
# author: Seong Yong-ju <sei40kr@gmail.com>

if ! hash todoist 2>/dev/null; then
    echo "ERROR: todoist was not found." >&2
    exit 1
fi

todoist list -f '(overdue | today)' | wc -l | gawk '
    {
        printf "<action=`google-chrome-stable --app=\\'https://todoist.com/app\\'`>"
        if ($1 == 0) printf "<fc=#999999><fn=6>\xef\x91\x9e</fn></fc>"
        else printf "<fn=6>\xef\x91\x9e</fn> " $1
        print "</action>"
    }'
