#!/usr/bin/env bash

# xmobar-fcitx
# author: Seong Yong-ju <sei40kr@gmail.com>

if ! hash fcitx-remote 2>/dev/null; then
    echo "ERROR: fcitx-remote was not found." >&2
    exit 1
fi

echo -n '<action=`fcitx-configtool`><fn=7>'

if [[ "$(fcitx-remote)" == 2 ]]; then
    echo -n 'あ'
else
    echo -n 'Aa'
fi

echo '</fn></action>'
