#!/usr/bin/env bash

# install --- Installer for dotfiles
# author: Seong Yong-ju <sei40kr@gmail.com>

BASEDIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

modules=(
    alacritty
    compton
    docker
    dunst
    fcitx
    feh
    fontconfig
    ghq
    psd
    redshift
    ripgrep
)


. "${BASEDIR}/install-scripts/utility.bash"

__facade_reducers=()

facade_add_reducer() {
    local reducer="$1"

    __facade_reducers+=( "$reducer" )
}

. "${BASEDIR}/install-scripts/arg-parser.bash"

parse_args "$@"

progress 'Collecting information ...'

# is_arch shouldn't be called repeatedly
# because it invokes a file access
is_arch=0
is_arch && is_arch=1

. "${BASEDIR}/install-scripts/module-utility.bash"

for module in "${modules_to_install[@]}"; do
    ctxpath="${BASEDIR}/install-scripts/modules/${module}"
    srcpaths=()

    [[ "$is_arch" == 1 ]] && srcpaths+=( "${ctxpath}/arch.bash" )
    is_macos && srcpaths+=( "${ctxpath}/macos.bash" )
    is_linux && srcpaths+=( "${ctxpath}/linux.bash" )
    srcpaths+=( "${ctxpath}/default.bash" )

    for srcpath in "${srcpaths[@]}"; do
        [[ -s "$srcpath" ]] && . "$srcpath"
    done
done


for reducer in "${__facade_reducers[@]}"; do
    eval "$reducer"
done


echo ''
