#!/bin/sh

# outdated-packages
# author: Seong Yong-ju <sei40kr@gmail.com>

homebrew_exec='/usr/local/bin/brew'
if [ -x "$homebrew_exec" ]; then
    outdated_homebrew=$("$homebrew_exec" outdated | wc -l)
fi

mas_exec='/usr/local/bin/mas'
if [ -x "$mas_exec" ]; then
    outdated_mas=$("$mas_exec" outdated | wc -l)
fi

echo $((outdated_homebrew + outdated_mas))
