#!/bin/sh

# fcitx
# author: Seong Yong-ju <sei40kr@gmail.com>

set -euo pipefail
IFS=$'\n\t'

case "$(fcitx-remote 2>/dev/null)" in
    2)
        echo 'あ'
        ;;
    *)
        echo 'Aa'
        ;;
esac
