#!/bin/sh

# cf http://beginners-guide-to-xmonad.readthedocs.io/configure_xsessionrc.html

# Load resources
xrdb -merge "${HOME}/.Xresources"
xmodmap "${HOME}/.Xmodmap"

# Set up an icon tray
stalonetray &

# Fire up apps
xscreensaver -no-splash &

if [ -x '/usr/bin/urxvtd' ]; then
  urxvtd -f -o -q
fi

if [ -x '/usr/bin/emacs' ]; then
  emacs --daemon
fi

if [ -x "/usr/bin/nm-applet" ]; then
  nm-applet --sm-disable &
fi

exec dbus-launch xmonad
