# -*- mode: sh -*-

# xinitrc
# author: Seong Yong-ju <sei40kr@gmail.com>

if [ -z "$XAUTHORITY" ]; then
  export XAUTHORITY="${HOME}/.Xauthority"
fi


export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS='@im=fcitx'
export DefaultIMModule=fcitx


if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  ## if not found, launch a new one
  eval "$(dbus-launch --sh-syntax)"
  echo "D-Bus per-session daemon address is: ${DBUS_SESSION_BUS_ADDRESS}"
fi

if ! hash dbus-launch 2>/dev/null; then
    echo 'WARN: dbus-launch is not installed.' >&2
    exec ~/.xsession
else
    exec dbus-launch --exit-with-session ~/.xsession 2>"${HOME}/.xsession-last-errors.log"
fi
