#!/usr/bin/env zsh

# xinit --- xinit
# author: Seong Yong-ju <sei40kr@gmail.com>

## Initialize

export LANG=ja-JP.UTF-8
export LC_CTYPE=ja-JP.UTF-8
export UNICODEMAP_JP='cp932,nec-vdc'


## Load resources

userresources="${HOME}/.Xresources"
usermodmap="${HOME}/.xmodmaprc"
sysresources='/etc/X11/xinit/Xresources'
sysmodmap='/etc/X11/xinit/Xmodmap'

if [[ -z "$XAUTHORITY" ]]; then
    XAUTHORITY="${HOME}/.Xauthority"
    export XAUTHORITY
fi

# merge in defaults and keymaps

if [[ -s "$sysresources" ]]; then
  xrdb -merge "$sysresources"
fi

if [[ -s "$sysmodmap" ]]; then
  xmodmap "$sysmodmap"
fi

if [ -s "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -s "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi


## Run start-up scripts

for apps in /etc/X11/xinit/xinitrc.d/*; do
  if [[ -x "$apps" ]]; then
    . "$apps"
  fi
done


## Launch daemons

# Launch Emacs server.
if hash emacs 2>/dev/null; then
   emacs --daemon &
fi
