#!/usr/bin/env zsh

# xsessionrc --- xsession initialization
# author: Seong Yong-ju <sei40kr@gmail.com>

# Use the Cabal packages
typeset -gU path
export path=( "${HOME}/.cabal/bin" $path )


## Load resources

xrdb -merge "${HOME}/.Xresources"
xmodmap "${HOME}/.xmodmaprc"


## Launch daemons

# Launch notification service
if hash dunst 2>/dev/null; then
  dunst &
fi

# Launch screensaver service
if hash xscreensaver 2>/dev/null; then
  xscreensaver -no-splash &
fi

# Launch urxvt daemon
if hash urxvtd 2>/dev/null; then
  urxvtd -f -o -q
fi


## Initialize IM

export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'
fcitx -rd &


## Launch apps

# Set the cursor
if hash xsetroot 2>/dev/null; then
  xsetroot -cursor_name left_ptr
fi

# Set the background image
if hash feh 2>/dev/null && [[ -s "${HOME}/.fehbg" ]]; then
  "${HOME}/.fehbg"
fi


## XMonad

if hash dbus-launch 2>/dev/null; then
  if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
    eval "$(dbus-launch --sh-syntax)"
  fi

  exec dbus-launch xmonad
else
  exec xmonad
fi
