#!/bin/sh

# toggle-chunkwm-layout
# author: Seong Yong-ju <sei40kr@gmail.com>

current_layout="$(chunkc tiling::query --desktop mode)"

case "$current_layout" in
    bsp )
        chunkc tiling::desktop --layout monocle
        ;;
    * )
        chunkc tiling::desktop --layout bsp
esac
