#!/bin/sh

# xmobar-arch-update
# author: Seong Yong-ju <sei40kr@gmail.com>

pkgs_to_update="$(pacman -Qu --color never | wc -l)"

if [ "$pkgs_to_update" -eq 0 ]; then
    echo -e '<fc=#00cc80><fn=3>\uf8d5</fn><fn=1>  </fn>up-to-date</fc>'
else
    echo -e "<fn=3>\uf8d6</fn><fn=1>  </fn>${pkgs_to_update}"
fi
