#!/bin/sh

# xmobar-alsa-vol
# author: Seong Yong-ju <sei40kr@gmail.com>

amixer sget Master | gawk '
/\[off\]/ {
  muted = 1
  print "<fc=#cc0080><fn=3>\xef\xb1\x9d</fn></fc>"
}
! muted {
  if (match($0, /\[([[:digit:]]{1,3})%\]/, matches)) {
    vol = matches[1] + 0
    if (vol == 0)       icon = "\xef\xaa\x80"
    else if (vol <= 33) icon = "\xef\xa9\xbe"
    else if (vol <= 66) icon = "\xef\xa9\xbf"
    else                icon = "\xef\xa9\xbd"

    printf "<fn=3>%s</fn>", icon
    printf (vol != 0 ? "<fn=1>  </fn>%d%%" : ""), vol
    print ""
  }
}'
