# alias_def_docker.fish
# author: Seong Yong-ju <sei40kr@gmail.com>

## almost from Prezto
alias -s dk docker
alias -s dka 'docker attach'
alias -s dkb 'docker build'
alias -s dkd 'docker diff'
alias -s dkdf 'docker system df'
alias -s dke 'docker exec'
alias -s dkE 'docker exec -it'
alias -s dkh 'docker history'
alias -s dki 'docker images'
alias -s dkin 'docker inspect'
alias -s dkim 'docker import'
alias -s dkk 'docker kill'
alias -s dkl 'docker logs'
alias -s dkli 'docker login'
alias -s dklo 'docker logout'
alias -s dkls 'docker ps'
alias -s dkp 'docker pause'
alias -s dkP 'docker unpause'
alias -s dkpl 'docker pull'
alias -s dkph 'docker push'
alias -s dkps 'docker ps'
alias -s dkpsa 'docker ps -a'
alias -s dkr 'docker run'
alias -s dkR 'docker run -it --rm'
alias -s dkRe 'docker run -it --rm --entrypoint /bin/bash'
alias -s dkRM 'docker system prune -af'
alias -s dkrm 'docker rm'
alias -s dkrmi 'docker rmi'
alias -s dkrn 'docker rename'
alias -s dks 'docker start'
alias -s dkS 'docker restart'
alias -s dkss 'docker stats'
alias -s dksv 'docker save'
alias -s dkt 'docker tag'
alias -s dktop 'docker top'
alias -s dkup 'docker update'
alias -s dkV 'docker volume'
alias -s dkv 'docker version'
alias -s dkw 'docker wait'
alias -s dkx 'docker stop'
# Container (C)
alias -s dkC 'docker container'
alias -s dkCa 'docker container attach'
alias -s dkCcp 'docker container cp'
alias -s dkCd 'docker container diff'
alias -s dkCe 'docker container exec'
alias -s dkCin 'docker container inspect'
alias -s dkCk 'docker container kill'
alias -s dkCl 'docker container logs'
alias -s dkCls 'docker container ls'
alias -s dkCp 'docker container pause'
alias -s dkCpr 'docker container prune'
alias -s dkCrn 'docker container rename'
alias -s dkCS 'docker container restart'
alias -s dkCrm 'docker container rm'
alias -s dkCr 'docker container run'
alias -s dkCR 'docker container run -it --rm'
alias -s dkCRe 'docker container run -it --rm --entrypoint /bin/bash'
alias -s dkCs 'docker container start'
alias -s dkCss 'docker container stats'
alias -s dkCx 'docker container stop'
alias -s dkCtop 'docker container top'
alias -s dkCP 'docker container unpause'
alias -s dkCup 'docker container update'
alias -s dkCw 'docker container wait'
# Image (I)
alias -s dkI 'docker image'
alias -s dkIb 'docker image build'
alias -s dkIh 'docker image history'
alias -s dkIim 'docker image import'
alias -s dkIin 'docker image inspect'
alias -s dkIls 'docker image ls'
alias -s dkIpr 'docker image prune'
alias -s dkIpl 'docker image pull'
alias -s dkIph 'docker image push'
alias -s dkIrm 'docker image rm'
alias -s dkIsv 'docker image save'
alias -s dkIt 'docker image tag'
# Volume (V)
alias -s dkV 'docker volume'
alias -s dkVin 'docker volume inspect'
alias -s dkVls 'docker volume ls'
alias -s dkVpr 'docker volume prune'
alias -s dkVrm 'docker volume rm'
# Network (N)
alias -s dkN 'docker network'
alias -s dkNs 'docker network connect'
alias -s dkNx 'docker network disconnect'
alias -s dkNin 'docker network inspect'
alias -s dkNls 'docker network ls'
alias -s dkNpr 'docker network prune'
alias -s dkNrm 'docker network rm'
# System (Y)
alias -s dkY 'docker system'
alias -s dkYdf 'docker system df'
alias -s dkYpr 'docker system prune'
# Stack (K)
alias -s dkK 'docker stack'
alias -s dkKls 'docker stack ls'
alias -s dkKps 'docker stack ps'
alias -s dkKrm 'docker stack rm'
# Swarm (W)
alias -s dkW 'docker swarm'

alias -s alpine-sh 'docker run -it --rm alpine:latest /bin/sh'
alias -s centos-bash 'docker run -it --rm centos:latest /bin/bash'
alias -s arch-bash 'docker run -it --rm base/archlinux:latest /bin/bash'
alias -s ubuntu-bash 'docker run -it --rm ubuntu:latest /bin/bash'
