" vimrc
" author: Seong Yong-ju <sei40kr@gmail.com>

"dein Scripts-----------------------------
if &compatible
  set nocompatible
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  " Let dein manage dein
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

  call dein#load_toml('~/.vim/dein.toml')

  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
syntax enable
"End dein Scripts-------------------------

let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors


inoremap jk <Esc>

" Move line up
nnoremap <silent> [e :move -2<CR>
" Move line down
nnoremap <silent> ]e :move +<CR>

" Insert space above
nnoremap <silent> [<Space> O<Esc>
" Insert space below
nnoremap <silent> ]<Space> o<Esc>

" Paste above current line
nnoremap <silent> [p P
" Paste below current line
nnoremap <silent> ]p p

" Smart up and down
nnoremap <Up> gk
nnoremap <Down> gj

" After paragraph motion go to first non-blank char (}^)
nnoremap } }^

" Indent to left and re-select
nnoremap < <<_
xnoremap < <gv
xnoremap <S-Tab> <gv
" Indent to right and re-select
nnoremap > >>_
xnoremap > >gv|
xnoremap <Tab> >gv|

" Navigation in command line
cnoremap <C-a> <Home>
" Move cursor backward in command line
cnoremap <C-b> <Left>
" Move cursor forward in command line
cnoremap <C-f> <Right>

" Move to split below (j)
nnoremap <silent> <Space>wj <C-w>j
" Move to upper split (k)
nnoremap <silent> <Space>wk <C-w>k
" Move to left split (h)
nnoremap <silent> <Space>wh <C-w>h
" Move to right split (l)
nnoremap <silent> <Space>wl <C-w>l
