#!/usr/bin/env bash

# xmobar-alsa-master-volume
# author: Seong Yong-ju <sei40kr@gmail.com>

if ! hash amixer 2>/dev/null; then
    echo "ERROR: amixer was not found." >&2
    exit 1
fi

amixer get Master | awk -F'[][]' '
    /dB/ {
        printf "<fn=6>"
        vol = substr($2, 0, length($2) - 1) + 0
        if ($6 == "off")    printf "\xef\xb1\x9d"
        else if (vol == 0)  printf "\xef\xaa\x80"
        else if (vol <= 33) printf "\xef\xa9\xbe"
        else if (vol <= 66) printf "\xef\xa9\xbf"
        else                printf "\xef\xa9\xbd"
        print "</fn>"
    }'
