#!/usr/bin/env bash

# xmobar-alsa-master-volume
# author: Seong Yong-ju <sei40kr@gmail.com>

if ! hash amixer 2>/dev/null; then
    echo "ERROR: amixer was not found." >&2
    exit 1
fi

volume="$(amixer get Master | grep -Poe '\[\d{1,3}%\]' | grep -Poe '\d+')"

if (( volume == 0 )); then
    printf '<fn=6>\ufa7e</fn>\n'
elif (( volume <= 50 )); then
    printf '<fn=6>\ufa7f</fn>\n'
else
    printf '<fn=6>\ufa7d</fn>\n'
fi
