#!/usr/bin/env bash

# xmobar-alsa-master-volume
# author: Seong Yong-ju <sei40kr@gmail.com>

if ! hash amixer 2>/dev/null; then
    echo "ERROR: amixer was not found." >&2
    exit 1
fi

amixer get Master | awk -F'[][]' '
    BEGIN { printf "<fn=6>" }
    /dB/ {
        if ($6 == "off")   printf "ﱝ"
        else if ($2 == 0)  printf "奄"
        else if ($2 <= 50) printf "奔"
        else               printf "墳"
    }
    END { print "</fn>" }'
