#!/usr/bin/env bash

# xmobar-fcitx-status
# author: Seong Yong-ju <sei40kr@gmail.com>

if ! hash fcitx-remote 2>/dev/null; then
    echo "ERROR: fcitx-remote was not found." >&2
    exit 1
fi

printf '<action=`fcitx-configtool`><fn=6>'

if [[ "$(fcitx-remote)" == 2 ]]; then
    printf 'あ'
else
    printf 'Aa'
fi

echo '</fn></action>'
