#!/usr/bin/env bash

# dmenurc
# author: Seong Yong-ju <sei40kr@gmail.com>

set -euo pipefail
IFS=$'\n\t'

dmenu_run -i -p '>' -fn 'Terminus\-ja-12' -nb '#333333' -nf '#999999' -sb '#0088cc' -sf '#ffffff'
