#!/usr/bin/env sh
# -*- mode: sh -*-

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_placement      exterior
yabai -m config window_border_width          3
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff368ee8
yabai -m config normal_window_border_color   0xffffffff
yabai -m config insert_window_border_color   0xffffffff
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  24
yabai -m config bottom_padding               24
yabai -m config left_padding                 24
yabai -m config right_padding                24
yabai -m config window_gap                   8

internet_ws=1
dev_ws=2
file_ws=3
im_ws=4
yabai -m rule --add app='^App Store$' manage=off sticky=on
yabai -m rule --add app='^Bitwarden$' manage=off sticky=on
yabai -m rule --add app='^Todoist$' manage=off sticky=on
yabai -m rule --add label='Utilities' app='^(Dictionary|Font Book|Digital Color Meter)$' manage=off sticky=on
yabai -m rule --add label='Preferences' app='^(System Preferences|Alfred Preferences|ConfigDialog|Logicool Options)$' manage=off sticky=on
yabai -m rule --add label='Web Browsers' app='^(Google Chrome|Safari)$' space="^${internet_ws}"
yabai -m rule --add label='Office Apps' app='^(Mail|Contacts|Calendar)$' space="^${internet_ws}"
yabai -m rule --add app='^Pocket$' space="^${internet_ws}"
yabai -m rule --add label='Terminal Apps' app='^(Alacritty|Terminal)$' space="^${dev_ws}"
yabai -m rule --add app='^Emacs$' title='^.' space="^${dev_ws}"
yabai -m rule --add app='^IntelliJ IDEA$' space="^${dev_ws}"
yabai -m rule --add app='^Dash$' space="^${dev_ws}"
yabai -m rule --add app='^Simulator$' space="^${dev_ws}" manage=off
yabai -m rule --add app='^Finder$' space="^${file_ws}"
yabai -m rule --add app='^Preview$' space="^${file_ws}"
yabai -m rule --add app='^(Slack|Discord|Gitter)$' space="^${im_ws}"
yabai -m rule --add app='^(Skype|LINE)$' space="^${im_ws}"

echo "yabai configuration loaded.."
