#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                off
# yabai -m config window_border_width          4
# yabai -m config normal_window_border_color   0xff505050
# yabai -m config insert_window_border_color   0xffd75f5f
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.6180
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  44
yabai -m config bottom_padding               24
yabai -m config left_padding                 24
yabai -m config right_padding                24
yabai -m config window_gap                   12

# app space settings
web_space=1
file_space=2
code_space=3
design_space=4
center_grid='26:26:5:5:16:16'
yabai -m rule --add app='Activity Monitor'      manage=off sticky=on grid="$center_grid"
yabai -m rule --add app='Alfred Preferences'    manage=off sticky=on grid="$center_grid"
yabai -m rule --add app='Bitwarden'             manage=off           grid="$center_grid"
yabai -m rule --add app='Calculator'            manage=off           grid="$center_grid"
yabai -m rule --add app='Calendar'              manage=off           grid="$center_grid"
yabai -m rule --add app='ConfigDialog' \
                    title='^Google Japanese Input Preferences$' \
                    manage=off sticky=on
yabai -m rule --add app='^Contacts$'            manage=off           grid="$center_grid"
yabai -m rule --add app='^Dictionary$'          manage=off           grid="$center_grid"
yabai -m rule --add app='^Digital Color Meter$' manage=off sticky=on grid="$center_grid"
yabai -m rule --add app='^Discord$'             manage=off           grid="$center_grid"
yabai -m rule --add app='^Disk Utility$'        manage=off sticky=on grid="$center_grid"
yabai -m rule --add app='^Font Book$'           manage=off sticky=on grid="$center_grid"
yabai -m rule --add app='^Gitter$'              manage=off           grid="$center_grid"
yabai -m rule --add app='^LINE$'                manage=off           grid="$center_grid"
yabai -m rule --add app='^Mail$'                manage=off           grid="$center_grid"
yabai -m rule --add app='^Maps$'                manage=off           grid="$center_grid"
yabai -m rule --add app='^Notes$'               manage=off           grid="$center_grid"
yabai -m rule --add app='^Photo Booth$'         manage=off           grid="$center_grid"
yabai -m rule --add app='^Reminders$'           manage=off           grid="$center_grid"
yabai -m rule --add app='^Skype$'               manage=off           grid="$center_grid"
yabai -m rule --add app='^Slack$'               manage=off           grid="$center_grid"
yabai -m rule --add app='^System Preferences$'  manage=off sticky=on
yabai -m rule --add app='^Todoist$'             manage=off           grid="$center_grid"
yabai -m rule --add app='^zoom\.us$'            manage=off           grid="$center_grid"
yabai -m rule --add app='^Google Chrome$'    space="^${web_space}"
yabai -m rule --add app='^Safari$'           space="^${web_space}"
yabai -m rule --add app='^Finder$'           space="^${file_space}"
yabai -m rule --add app='^Preview$'          space="^${file_space}"  manage=off grid="$center_grid"
yabai -m rule --add app='^QuickTime Player$' space="^${file_space}"  manage=off grid="$center_grid"
yabai -m rule --add app='^Alacritty$'        space="^${code_space}"
yabai -m rule --add app='^Dash$'             space="^${code_space}"  manage=off grid="$center_grid"
yabai -m rule --add app='^Emacs$'            space="^${code_space}"
yabai -m rule --add app='^Electron$' \
                    title=' - vmd$' \
                    space="^${code_space}"
yabai -m rule --add app='^IntelliJ IDEA$'    space="^${code_space}"
yabai -m rule --add app='^IntelliJ IDEA$' \
                    title='^Welcome to IntelliJ IDEA$' \
                    manage=off
yabai -m rule --add app='^Simulator$'        space="^${code_space}"  manage=off
yabai -m rule --add app='^Photoshop CC$'     space="^${design_space}"
yabai -m rule --add app='^Pixelmator Pro$'   space="^${design_space}"
yabai -m rule --add app='^Sketch$'           space="^${design_space}"

# ubersicht integration settings
ubersicht_app="/Applications/Übersicht.app"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"${ubersicht_app}\" to refresh widget id \"yabai-spaces-widget-yabai-spaces-jsx\"'"

echo 'yabai configuration loaded..'
