#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config window_border                off
# yabai -m config window_border_width          4
# yabai -m config normal_window_border_color   0xff505050
# yabai -m config insert_window_border_color   0xffd75f5f
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.6180
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  56
yabai -m config bottom_padding               56
yabai -m config left_padding                 24
yabai -m config right_padding                24
yabai -m config window_gap                   12

ubersicht_app="/Applications/Übersicht.app"
refresh_spaces="osascript -e 'tell application \"${ubersicht_app}\" to refresh widget id \"yabai-spaces-widget-yabai-spaces-jsx\"'"
refresh_active_window="osascript -e 'tell application \"${ubersicht_app}\" to refresh widget id \"yabai-active-window-widget-yabai-active-window-jsx\"'"
yabai -m signal --add event=space_changed        action="$refresh_spaces"
yabai -m signal --add event=window_focused       action="$refresh_active_window"
yabai -m signal --add event=window_title_changed action="$refresh_active_window"

echo 'yabai configuration loaded..'
