#!/bin/sh

pop="$(curl -s "https://api.openweathermap.org/data/2.5/forecast?id=1850147&appid=${KEY}&cnt=1" | jq '.list[0].pop * 100 | floor')"

if [[ "$pop" -lt 40 ]]; then
  icon='羚'
else
  icon='%{F#51afef}%{F-}'
fi

echo "%{T2}${icon}%{T-} ${pop}%"
