#!/bin/sh

title="$(xdotool search --classname crx_cinhimbnkkaeohfgghhklpknlkffjgod getwindowname)"
title="${title% - YouTube Music}"
title="${title/YouTube Music}"

echo "${title:+%{T2\}%{F#ff0000\}%{F-\}%{T-\}  ${title}}"
