# alias_def_java.fish
# author: Seong Yong-ju <sei40kr@gmail.com>

# mvn
alias mvncie 'mvn clean install eclipse:eclipse'
alias mvnci 'mvn clean install'
alias mvncist 'mvn clean install -DskipTests'
alias mvncisto 'mvn clean install -DskipTests --offline'
alias mvne 'mvn eclipse:eclipse'
alias mvnce 'mvn clean eclipse:clean eclipse:eclipse'
alias mvncv 'mvn clean verify'
alias mvnd 'mvn deploy'
alias mvnp 'mvn package'
alias mvnc 'mvn clean'
alias mvncom 'mvn compile'
alias mvnct 'mvn clean test'
alias mvnt 'mvn test'
alias mvnag 'mvn archetype:generate'
alias mvn-updates 'mvn versions:display-dependency-updates'
alias mvntc7 'mvn tomcat7:run'
alias mvntc 'mvn tomcat:run'
alias mvnjetty 'mvn jetty:run'
alias mvndt 'mvn dependency:tree'
alias mvns 'mvn site'
alias mvnsrc 'mvn dependency:sources'
alias mvndocs 'mvn dependency:resolve -Dclassifier=javadoc'
