# alias_def_docker.fish
# author: Seong Yong-ju <sei40kr@gmail.com>

## almost from Prezto
alias dk docker
alias dka 'docker attach'
alias dkb 'docker build'
alias dkd 'docker diff'
alias dkdf 'docker system df'
alias dke 'docker exec'
alias dkE 'docker exec -it'
alias dkh 'docker history'
alias dki 'docker images'
alias dkin 'docker inspect'
alias dkim 'docker import'
alias dkk 'docker kill'
alias dkl 'docker logs'
alias dkli 'docker login'
alias dklo 'docker logout'
alias dkls 'docker ps'
alias dkp 'docker pause'
alias dkP 'docker unpause'
alias dkpl 'docker pull'
alias dkph 'docker push'
alias dkps 'docker ps'
alias dkpsa 'docker ps -a'
alias dkr 'docker run'
alias dkR 'docker run -it --rm'
alias dkRe 'docker run -it --rm --entrypoint /bin/bash'
alias dkRM 'docker system prune -af'
alias dkrm 'docker rm'
alias dkrmi 'docker rmi'
alias dkrn 'docker rename'
alias dks 'docker start'
alias dkS 'docker restart'
alias dkss 'docker stats'
alias dksv 'docker save'
alias dkt 'docker tag'
alias dktop 'docker top'
alias dkup 'docker update'
alias dkV 'docker volume'
alias dkv 'docker version'
alias dkw 'docker wait'
alias dkx 'docker stop'
# Container (C)
alias dkC 'docker container'
alias dkCa 'docker container attach'
alias dkCcp 'docker container cp'
alias dkCd 'docker container diff'
alias dkCe 'docker container exec'
alias dkCin 'docker container inspect'
alias dkCk 'docker container kill'
alias dkCl 'docker container logs'
alias dkCls 'docker container ls'
alias dkCp 'docker container pause'
alias dkCpr 'docker container prune'
alias dkCrn 'docker container rename'
alias dkCS 'docker container restart'
alias dkCrm 'docker container rm'
alias dkCr 'docker container run'
alias dkCR 'docker container run -it --rm'
alias dkCRe 'docker container run -it --rm --entrypoint /bin/bash'
alias dkCs 'docker container start'
alias dkCss 'docker container stats'
alias dkCx 'docker container stop'
alias dkCtop 'docker container top'
alias dkCP 'docker container unpause'
alias dkCup 'docker container update'
alias dkCw 'docker container wait'
# Image (I)
alias dkI 'docker image'
alias dkIb 'docker image build'
alias dkIh 'docker image history'
alias dkIim 'docker image import'
alias dkIin 'docker image inspect'
alias dkIls 'docker image ls'
alias dkIpr 'docker image prune'
alias dkIpl 'docker image pull'
alias dkIph 'docker image push'
alias dkIrm 'docker image rm'
alias dkIsv 'docker image save'
alias dkIt 'docker image tag'
# Volume (V)
alias dkV 'docker volume'
alias dkVin 'docker volume inspect'
alias dkVls 'docker volume ls'
alias dkVpr 'docker volume prune'
alias dkVrm 'docker volume rm'
# Network (N)
alias dkN 'docker network'
alias dkNs 'docker network connect'
alias dkNx 'docker network disconnect'
alias dkNin 'docker network inspect'
alias dkNls 'docker network ls'
alias dkNpr 'docker network prune'
alias dkNrm 'docker network rm'
# System (Y)
alias dkY 'docker system'
alias dkYdf 'docker system df'
alias dkYpr 'docker system prune'
# Stack (K)
alias dkK 'docker stack'
alias dkKls 'docker stack ls'
alias dkKps 'docker stack ps'
alias dkKrm 'docker stack rm'
# Swarm (W)
alias dkW 'docker swarm'

alias alpine-sh 'docker run -it --rm alpine:latest /bin/sh'
alias centos-bash 'docker run -it --rm centos:latest /bin/bash'
alias arch-bash 'docker run -it --rm base/archlinux:latest /bin/bash'
alias ubuntu-bash 'docker run -it --rm ubuntu:latest /bin/bash'
