# balias_def_java.fish
# author: Seong Yong-ju <sei40kr@gmail.com>

# mvn
balias mvncie 'mvn clean install eclipse:eclipse'
balias mvnci 'mvn clean install'
balias mvncist 'mvn clean install -DskipTests'
balias mvncisto 'mvn clean install -DskipTests --offline'
balias mvne 'mvn eclipse:eclipse'
balias mvnce 'mvn clean eclipse:clean eclipse:eclipse'
balias mvncv 'mvn clean verify'
balias mvnd 'mvn deploy'
balias mvnp 'mvn package'
balias mvnc 'mvn clean'
balias mvncom 'mvn compile'
balias mvnct 'mvn clean test'
balias mvnt 'mvn test'
balias mvnag 'mvn archetype:generate'
balias mvn-updates 'mvn versions:display-dependency-updates'
balias mvntc7 'mvn tomcat7:run'
balias mvntc 'mvn tomcat:run'
balias mvnjetty 'mvn jetty:run'
balias mvndt 'mvn dependency:tree'
balias mvns 'mvn site'
balias mvnsrc 'mvn dependency:sources'
balias mvndocs 'mvn dependency:resolve -Dclassifier=javadoc'
