{ inputs, ... }:

{
  imports = [
    inputs.self.homeModules.agent-browser
    inputs.self.homeModules.ai-shared
    inputs.self.homeModules.ansible
    inputs.self.homeModules.anyrun
    inputs.self.homeModules.atuin
    inputs.self.homeModules.aws
    inputs.self.homeModules.azure
    inputs.self.homeModules.bitwarden
    inputs.self.homeModules.browser-shared
    inputs.self.homeModules.cc
    inputs.self.homeModules.claude-code
    inputs.self.homeModules.codex
    inputs.self.homeModules.crush
    inputs.self.homeModules.difftastic
    inputs.self.homeModules.docker
    inputs.self.homeModules.dunst
    inputs.self.homeModules.editor-shared
    inputs.self.homeModules.emacs
    inputs.self.homeModules.fastfetch
    inputs.self.homeModules.fcitx5
    inputs.self.homeModules.firefox
    inputs.self.homeModules.foliate
    inputs.self.homeModules.gemini-cli
    inputs.self.homeModules.gimp
    inputs.self.homeModules.git
    inputs.self.homeModules.github
    inputs.self.homeModules.gitu
    inputs.self.homeModules.gnome-pomodoro
    inputs.self.homeModules.go
    inputs.self.homeModules.graphite-theme
    inputs.self.homeModules.haskell
    inputs.self.homeModules.helix
    inputs.self.homeModules.idea
    inputs.self.homeModules.ideavim
    inputs.self.homeModules.inkscape
    inputs.self.homeModules.java
    inputs.self.homeModules.javascript
    inputs.self.homeModules.julia
    inputs.self.homeModules.jupyter
    inputs.self.homeModules.k8s
    inputs.self.homeModules.kitty
    inputs.self.homeModules.kotlin
    inputs.self.homeModules.latex
    inputs.self.homeModules.lazyvim
    inputs.self.homeModules.lean
    inputs.self.homeModules.lua
    inputs.self.homeModules.nix
    inputs.self.homeModules.nushell
    inputs.self.homeModules.obs-studio
    inputs.self.homeModules.oj
    inputs.self.homeModules.orchis-theme
    inputs.self.homeModules.prisma
    inputs.self.homeModules.python
    inputs.self.homeModules.qml
    inputs.self.homeModules.quickshell
    inputs.self.homeModules.r
    inputs.self.homeModules.ripgrep
    inputs.self.homeModules.ruby
    inputs.self.homeModules.rust
    inputs.self.homeModules.sensible-terminal
    inputs.self.homeModules.shell
    inputs.self.homeModules.shell-shared
    inputs.self.homeModules.solidity
    inputs.self.homeModules.sql
    inputs.self.homeModules.starship
    inputs.self.homeModules.swww
    inputs.self.homeModules.term-shared
    inputs.self.homeModules.terraform
    inputs.self.homeModules.tokyo-night
    inputs.self.homeModules.tmux
    inputs.self.homeModules.web
    inputs.self.homeModules.wezterm
    inputs.self.homeModules.workmux
    inputs.self.homeModules.whitesur-theme
    inputs.self.homeModules.yazi
    inputs.self.homeModules.zathura
    inputs.self.homeModules.zed
    inputs.self.homeModules.zsh
  ];
}
