# -*- mode: sh; sh-shell: zsh -*-

KEYTIMEOUT=1
bindkey -e
bindkey '^u' backward-kill-line
autoload -Uz select-word-style
select-word-style bash

setopt APPEND_HISTORY \
       AUTO_LIST \
       AUTO_MENU \
       AUTO_PARAM_KEYS \
       AUTO_PARAM_SLASH \
       AUTO_PUSHD \
       AUTO_RESUME \
       EQUALS GLOB_DOTS \
       HIST_FCNTL_LOCK \
       HIST_IGNORE_DUPS \
       HIST_IGNORE_SPACE \
       HIST_REDUCE_BLANKS \
       INTERACTIVE_COMMENTS \
       NO_BEEP \
       NUMERIC_GLOB_SORT \
       PRINT_EIGHT_BIT \
       PROMPT_SUBST \
       PUSHD_IGNORE_DUPS \
       SHARE_HISTORY
unsetopt LIST_BEEP

HISTSIZE=10000
SAVEHIST=10000

declare -A ZINIT
ZINIT[BIN_DIR]="@zinit@/share/zinit"
. "${ZINIT[BIN_DIR]}/zinit.zsh"

## Commands

zinit ice trigger-load '!extract;!x' id-as'OMZP::extract'
zinit snippet '@oh_my_zsh@/share/oh-my-zsh/plugins/extract/extract.plugin.zsh'

if [[ "$OSTYPE" == darwin* ]]; then
  zinit ice id-as'PZT::modules--gnu-utility'
  zinit light '@zsh_prezto@/modules/gnu-utility'
fi

## Shell Enhancements

zinit ice wait'0' lucid
zinit light '@zsh_autosuggestions@/share/zsh-autosuggestions'

zinit ice wait'0' lucid
zinit light '@zsh_autopair@/share/zsh/zsh-autopair'

zinit ice wait'0' atinit'zpcompinit; zpcdreplay' lucid
zinit light '@zsh_fast_syntax_highlighting@/share/zsh/site-functions'

zinit ice wait'0' lucid
zinit light '@zsh_history_search_multi_word@/share/zsh/zsh-history-search-multi-word'

zinit light '@zsh_smart_history@/share/zsh/plugins/zsh-smart-history'

if [[ -n "$TMUX" ]]; then
  zinit light '@zsh_tmux_man@/share/zsh/plugins/zsh-tmux-man'
  # Remove alias run-help=man
  if [[ ${+aliases[run-help]} == 1 ]]; then
    unalias run-help
  fi
fi

zinit ice id-as'OMZP::bgnotify'
zinit snippet '@oh_my_zsh@/share/oh-my-zsh/plugins/bgnotify/bgnotify.plugin.zsh'

zinit ice id-as'OMZL::clipboard.zsh'
zinit snippet '@oh_my_zsh@/share/oh-my-zsh/lib/clipboard.zsh'

HYPHEN_INSENSITIVE=true
zinit ice id-as'OMZL::completion.zsh'
zinit snippet '@oh_my_zsh@/share/oh-my-zsh/lib/completion.zsh'

zinit ice from'gh-r' ver'v2.19.0' as'program' atclone'./navi widget zsh >zhook.zsh' atpull'%atclone' src'zhook.zsh'
zinit light denisidoro/navi

## Key Bindings

zinit ice id-as'OMZP::fancy-ctrl-z'
zinit snippet '@oh_my_zsh@/share/oh-my-zsh/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh'

FZF_DEFAULT_OPTS='--cycle --reverse --info=inline'
FZF_DEFAULT_COMMAND='@fd@/bin/fd -HL -t f -E .git'
FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
FZF_CTRL_T_OPTS="--preview='@bat@/bin/bat -pp --color=always {}'"
FZF_ALT_C_OPTS="--preview='@exa@/bin/exa -la {}'"
FZF_TMUX=1
FZF_TMUX_OPTS='-p 80%,80%'
zinit ice bindmap'^R->;\\ec->' multisrc'{completion,key-bindings}.zsh'
zinit light '@fzf@/share/fzf'

## Prompt

eval "$(starship init zsh)"

# vim: set ft=zsh
