#!/bin/sh

# dmenurc
# author: Seong Yong-ju <sei40kr@gmail.com>

BASE='#b2b2b2'
BG1='#292b2e'
HIGHLIGHT='#444155'

dmenu -b \
    -i \
    -l 15 \
    -fn 'Terminus\-ja-12' \
    -nb "$BG1" \
    -nf "$BASE" \
    -sb "$HIGHLIGHT" \
    -sf "$BASE"
