#!/bin/sh

# build
# author: Seong Yong-ju <sei40kr@gmail.com>

stack build :custom-xmonad --verbosity error
stack install :custom-xmonad --local-bin-path . --verbosity error
mv custom-xmonad xmonad-x86_64-linux
