#-*- mode: sh -*-

# xinitrc --- Shared environment setup for graphical sessions
# author: Seong Yong-ju <sei40kr@gmail.com>

# Make sure this is before the 'exec' command or it won't be sourced.
if [[ -f /etc/xprofile ]]; then
    . /etc/xprofile
fi
if [[ -f "${HOME}/.xprofile" ]]; then
    . "${HOME}/.xprofile"
fi

for file in /etc/X11/xinit/xinitrc.d/*; do
    . "$file"
done

# Load X defaults. This should probably be safe on wayland too.
if [[ -f /etc/X11/xinit/.Xresources ]]; then
    xrdb -merge /etc/X11/xinit/.Xresources
fi
if [[ -f /etc/X11/xinit/.Xmodmap ]]; then
    xmodmap /etc/X11/xinit/.Xmodmap
fi
if [[ -f "${HOME}/.Xresources" ]]; then
    xrdb -merge "${HOME}/.Xresources"
fi
if [[ -f "${HOME}/.Xmodmap" ]]; then
    xmodmap "${HOME}/.Xmodmap"
fi

# Allow the user to execute commands at the beginning of the X session
if [[ -f "${HOME}/.xprofile" ]]; then
    . "${HOME}/.xprofile"
fi

# Allow the user to setup a custom session type
if [[ -x "${HOME}/.xsession" ]]; then
    if hash dbus-launch 2>/dev/null && [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
        exec dbus-launch --exit-with-session "${HOME}/.xsession" \
             2>"${HOME}/.xsession-errors"
    else
        exec "${HOME}/.xsession" 2>"${HOME}/.xsession-errors"
    fi
fi
