#!/bin/sh

userresources="${HOME}/.Xresources"
usermodmap="${HOME}/.Xmodmap"
sysresources='/etc/X11/xinit/.Xresources'
sysmodmap='/etc/X11/xinit/.Xmodmap'

# merge in defaults and keymaps

if [ -f "$sysresources" ]; then
  xrdb -merge "$sysresources"
fi

if [ -f "$sysmodmap" ]; then
  xmodmap "$sysmodmap"
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

if [ -z "$XAUTHORITY" ]; then
  export XAUTHORITY="${HOME}/.Xauthority"
fi

# start some nice programs

emacs --daemon &

if [ -d '/etc/X11/xinit/xinitrc.d' ] ; then
  for f in '/etc/X11/xinit/xinitrc.d/'?*.sh ; do
    # shellcheck disable=SC1090
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

exec i3
