#!/bin/sh

if [ -z "$XAUTHORITY" ]; then
  export XAUTHORITY="${HOME}/.Xauthority"
fi

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS='@im=fcitx'
export DefaultIMModule=fcitx

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  ## if not found, launch a new one
  eval "$(dbus-launch --sh-syntax)"
  echo "D-Bus per-session daemon address is: ${DBUS_SESSION_BUS_ADDRESS}"
fi
