#!/usr/bin/env bash

# xsession
# author: Seong Yong-ju <sei40kr@gmail.com>

xset r rate 150 30
xsetroot -cursor_name left_ptr

if hash compton 2>/dev/null; then
    compton -b
fi

if hash redshift 2>/dev/null; then
    redshift &
fi

if hash fcitx-autostart 2>/dev/null; then
    fcitx-autostart &
fi

# Start the window manager
if hash xmonad 2>/dev/null; then
    xmonad
fi
