#!/usr/bin/env bash

# xsession
# author: Seong Yong-ju <sei40kr@gmail.com>

xset r rate 150 30
xsetroot -cursor_name left_ptr

if hash xautolock 2>/dev/null && hash xsecurelock 2>/dev/null; then
    XSECURELOCK_AUTH_BACKGROUND_COLOR='#282c34' \
                                     XSECURELOCK_AUTH_FOREGROUND_COLOR='#bbc2cf' \
                                     XSECURELOCK_FONT='sans\-serif-13' \
                                     XSECURELOCK_PASSWORD_PROMPT=asterisks \
                                     xautolock -locker xsecurelock -resetsaver -detectsleep &
fi

if [[ -x /usr/bin/compton ]]; then
    /usr/bin/compton &
fi

if hash redshift 2>/dev/null; then
    redshift &
fi

if [[ -x /usr/bin/xwinwrap && -x /usr/lib/xscreensaver/glslideshow ]]; then
    /usr/bin/xwinwrap -fs -b -nf -ov -- \
             /usr/lib/xscreensaver/glslideshow -root -duration 180 -zoom 100 -clip -window-id WID &
fi

if [[ -x /usr/bin/dunst ]]; then
    /usr/bin/dunst &
fi

if hash fcitx-autostart 2>/dev/null; then
    export XMODIFIERS='@im=fcitx'
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export DefaultIMModule=fcitx

    fcitx-autostart &
fi

# Start the window manager
if hash xmonad 2>/dev/null; then
    xmonad
fi
