#!/usr/bin/env bash

# xsession
# author: Seong Yong-ju <sei40kr@gmail.com>

xset r rate 150 30
xsetroot -cursor_name left_ptr

if [[ -x /usr/bin/picom ]]; then
    /usr/bin/picom &
fi

if [[ -x /usr/bin/gnome-keyring-daemon ]]; then
    eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
    export SSH_AUTH_SOCK
fi

if [[ -x "${HOME}/.local/bin/wallpaper.sh" ]]; then
    "${HOME}/.local/bin/wallpaper.sh" &
fi

if [[ -x /usr/bin/xautolock && -x /usr/bin/gnome-screensaver-command ]]; then
    /usr/bin/xautolock -locker '/usr/bin/gnome-screensaver-command -l' \
                       -resetsaver \
                       -detectsleep &
fi

if [[ -x /usr/bin/dunst ]]; then
    /usr/bin/dunst &
fi

if [[ -x /usr/bin/fcitx-autostart ]]; then
    export XMODIFIERS='@im=fcitx'
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export DefaultIMModule=fcitx
    /usr/bin/fcitx-autostart &
fi

if [[ -x /usr/bin/geary ]]; then
    /usr/bin/geary --gapplication-service &
fi

if [[ -x /usr/lib/evolution-data-server/evolution-alarm-notify ]]; then
    /usr/lib/evolution-data-server/evolution-alarm-notify &
fi

if [[ -x /usr/bin/gnome-pomodoro ]]; then
    /usr/bin/gnome-pomodoro --no-default-window &
fi

if [[ -x /usr/bin/dropbox ]]; then
    /usr/bin/dropbox &
fi

export XDG_SESSION_TYPE=x11
export XDG_CURRENT_DESKTOP='GNOME-Flashback:GNOME'
export GDK_BACKEND=x11

rm -f /tmp/.xmonad-workspace-log
mkfifo /tmp/.xmonad-workspace-log

# Polybar
if [[ -x /usr/bin/polybar ]]; then
    /usr/bin/polybar -r top &
    /usr/bin/polybar -r bottom &
fi

# GNOME Flashback with Xmonad
gnome-session --builtin -a /dev/null --session=xmonad --disable-acceleration-check
