#!/bin/sh

# ram-usage
# author: Seong Yong-ju <sei40kr@gmail.com>

psize="$(sysctl -nq 'vm.pagesize')"

vm_stat | awk -v psize="$psize" '
/^Pages (active|wired down):/{used+=$NF}
/^Pages (free|inactive|speculative|occupied by compressor):/{free+=$NF}
END{print used*psize,free*psize}'