#!/usr/bin/env bash

# install
# author: Seong Yong-ju <sei40kr@gmail.com>

IFS=$'\n\t'

: "${XDG_CONFIG_HOME:=${HOME}/.config}"
: "${XDG_DATA_HOME:=${HOME}/.local/share}"

: "${XDG_PICTURES_DIR:=${HOME}/Pictures}"

: "${WORKSPACE_DIR:=${HOME}/projects}"

: "${ZDOTDIR:=${HOME}/.zsh}"

: "${DOOMDIR:=${HOME}/.doom.d}"

: "${NVM_DIR:=${HOME}/.nvm}"
: "${GOENV_ROOT:=${HOME}/.goenv}"
: "${GOPATH:=${HOME}/go/system}"
: "${JENV_ROOT:=${HOME}/.jenv}"
: "${PYENV_ROOT:=${HOME}/.pyenv}"
: "${RBENV_ROOT:=${HOME}/.rbenv}"
: "${PERLBREW_ROOT:=${HOME}/perl5/perlbrew}"
: "${R_ENVIRON_USER:=${XDG_CONFIG_HOME}/r/.Renviron}"
: "${R_PROFILE_USER:=${XDG_CONFIG_HOME}/r/.Rprofile.r}"

declare ZINIT_HOME_DIR="${HOME}/.zinit"
declare ZINIT_BIN_DIR="${ZINIT_HOME_DIR}/bin"

basepath="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/core.bash
. "${basepath}/install/lib/core.bash"
# shellcheck source=lib/simple-tui/simple-tui.bash
. "${basepath}/install/lib/simple-tui/simple-tui.bash"
# shellcheck source=lib/errors.bash
. "${basepath}/install/lib/errors.bash"
# shellcheck source=lib/assertions.bash
. "${basepath}/install/lib/assertions.bash"
# shellcheck source=lib/module.bash
. "${basepath}/install/lib/module.bash"
# shellcheck source=lib/tui.bash
. "${basepath}/install/lib/tui.bash"
# shellcheck source=lib/tui_select.bash
. "${basepath}/install/lib/tui_select.bash"
# shellcheck source=lib/process.bash
. "${basepath}/install/lib/process.bash"
# shellcheck source=lib/facades/brew.bash
# shellcheck source=lib/facades/gem.bash
# shellcheck source=lib/facades/git.bash
# shellcheck source=lib/facades/go.bash
# shellcheck source=lib/facades/goenv.bash
# shellcheck source=lib/facades/nvm.bash
# shellcheck source=lib/facades/pacman.bash
# shellcheck source=lib/facades/pip.bash
# shellcheck source=lib/facades/pyenv.bash
# shellcheck source=lib/facades/r.bash
# shellcheck source=lib/facades/rbenv.bash
# shellcheck source=lib/facades/rustup.bash
# shellcheck source=lib/facades/stack.bash
# shellcheck source=lib/facades/systemctl.bash
# shellcheck source=lib/facades/trizen.bash
# shellcheck source=lib/facades/yarn.bash
for file in ${basepath}/install/lib/facades/*.bash; do
  . "$file"
done

# shellcheck source=system_setup.bash
# shellcheck source=desktop_environment.bash
# shellcheck source=apps/index.bash
# shellcheck source=tools.bash
# shellcheck source=shell_environment/index.bash
# shellcheck source=development_environment/index.bash
use_lazy_modules \
  system_setup system_setup \
  desktop_environment install_desktop_environment \
  apps install_apps \
  tools install_tools \
  shell_environment install_shell_environment \
  development_environment install_development_environment

while true; do
  print_title 'dotfiles'

  tui_init_options
  tui_add_options \
    'System Setup' system_setup \
    'Desktop Environment' install_desktop_environment \
    'Apps' install_apps \
    'Tools' install_tools \
    'Shell Environment' install_shell_environment \
    'Development Environment' install_development_environment
  tui_set_quit_option q 'Quit'

  if ! tui_select_option 'Enter your option'; then
    break
  fi
done
