#!/usr/bin/env zsh

function drmi() {
  docker image ls \
      | fzf --header-lines=1 --multi --reverse \
      | perl -alne '{ print $F[2] }' \
      | xargs docker rmi
}

drmi "$@"

# vi: ft=zsh et sw=2 cc=80

