#!/usr/bin/env bash

# rofi-system-menu --- Show a system menu using Rofi
# author: Seong Yong-ju <sei40kr@gmail.com>

suspend='Suspend'
reboot='Reboot'
shutdown='Shutdown'

action="$(cat <<EOM | rofi -dmenu -p 'system'
${suspend}
${reboot}
${shutdown}
EOM
)"

case "$action" in
    "$suspend" )
        systemctl suspend -i
        ;;
    "$reboot" )
        systemctl reboot -i
        ;;
    "$shutdown" )
        systemctl poweroff -i
        ;;
esac
