#!/bin/sh

# tmux-cpu-usage
# author: Seong Yong-ju <sei40kr@gmail.com>

S_TIME_FORMAT=ISO mpstat -P ALL 1 | awk '
$2 == "all" {
  idle = $12 + 0
  usage = int(100 - idle)

  s = "\xef\xac\x99 " usage "%"

  if (30 <= usage) {
    if (usage <= 80) color = "#cc8000"
    else             color = "#cc0080"

    s = "#[fg=" color "]" s "#[default]"
  }

  print s
  fflush()
}'
