#!/bin/sh

# tmux-mem-usage
# author: Seong Yong-ju <sei40kr@gmail.com>

free -ms 1 | awk '
$1 == "Mem:" {
  total = $2 + 0
  used = $3 + 0
  usage = used / total

  s = "\xef\xa1\x9a " used "M"

  if (0.30 <= usage) {
    if (usage <= 0.80) color = "#cc8000"
    else               color = "#cc0080"

    s = "#[fg=" color "]" s "#[default]"
  }

  print s
  fflush()
}'
