# -*- mode: sh -*-

# bashrc
# author: Seong Yong-ju <sei40kr@gmail.com>

if [[ "$XDG_VTNR" == 1 ]] && [[ "$DISPLAY" == 0 ]] && hash startx 2>/dev/null; then
    exec startx
elif [[ "$OSTYPE" == darwin* ]] && [[ "$TMUX" == "" ]] && hash tmux 2>/dev/null; then
    exec tmux
elif hash fish 2>/dev/null; then
    exec fish
fi
