#!/bin/sh

if [ -z "$XDG_DATA_HOME" ]; then
    XDG_DATA_HOME="${HOME}/.local/share"
fi

while true; do
    file="$(find "${XDG_DATA_HOME}/backgrounds" \
                 -mindepth 1 \
                 -maxdepth 1 \
                 -type f \
                 \( -name '*.jpg' -o -name '*.png' \) |
                 shuf -n1)"
    feh --bg-fill --no-fehbg "$file"

    sleep 5m
done
